# https://pre-commit.com/
default_stages: [commit]

default_language_version:
  python: python3.10

repos:

  - repo: local

    hooks:
      - id: black
        name: black
        entry: black
        language: system
        types: [python]

      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
